- name: Deploy AS3 Declaration
  hosts: tag_Ansible_ltm:!tag_environment_gold # select all ltm BIG-IPs except those in the gold environment
  connection: local
  vars:
    base_git_repo_path: "{{ playbook_dir }}/files/policy"
    git_url: "git@example.local"
    git_key: "{{ lookup('file','~/.ssh/id_rsa') }}"
    git_repo_path: "{{ playbook_dir }}/files/policy"
    git_msg: "asm policy update"
    git_local_only: true
    staging_tag: "tag_purpose_test"  
    provider:
      server: "{{ ansible_host }}"
      user: admin
      password: "{{ lookup('env','BIGIP_PASSWORD') }}"
      validate_certs: false
      server_port: 443
  gather_facts: false
  any_errors_fatal: true

  tasks:
  - name: Deploy the app service configuration from master branch 
    include_role:
      name: f5devcentral.atc_deploy
    vars:
      atc_service: AS3
      atc_method: POST
      atc_declaration_file: "{{ playbook_dir }}/files/policy/master/LTM_configuration/declaration-master.json"
    when: 'staging_tag not in group_names'

  - name: Deploy the app service configuration from staging branch 
    include_role:
      name: f5devcentral.atc_deploy
    vars:
      atc_service: AS3
      atc_method: POST
      atc_declaration_file: "{{ playbook_dir }}/files/policy/staging/LTM_configuration/declaration-staging.json"
    when: 'staging_tag in group_names'

