- name: Import BIG-IP Security Policies
  hosts: tag_Ansible_ltm:!tag_environment_gold # select all ltm BIG-IPs except those in the gold environment
  connection: local
  vars:
    base_git_repo_path: "{{ playbook_dir }}/files/policy"
    git_url: "git@example.local"
    git_key: "{{ lookup('file','~/.ssh/id_rsa') }}"
    git_repo_path: "{{ playbook_dir }}/files/policy"
    git_msg: "asm policy update"
    git_local_only: true
    staging_tag: "tag_purpose_test"  
    provider:
      server: "{{ ansible_host }}"
      user: admin
      password: "{{ lookup('env','BIGIP_PASSWORD') }}"
      validate_certs: false
      server_port: 443
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: Retrieve Latest master branch
      run_once: true
      vars:
        git_repo_path: "{{ base_git_repo_path }}/master"
        git_remove_local: false
        git_version: "master"
      include_role:
        name: ansible-git
        tasks_from: pull
      when: 'git_local_only != true'     

    - name: Retrieve Staging branch
      run_once: true
      vars:
        git_repo_path: "{{ base_git_repo_path }}/staging"
        git_remove_local: false
        git_version: "staging"
      include_role:
        name: ansible-git
        tasks_from: pull
      when: 'git_local_only != true'   
    
    - name: Load master LTM configuration
      bigip_config:
        merge_content: "{{ lookup('file', '{{ base_git_repo_path }}/master/LTM_configuration/tmsh.config' ) }}"
        provider: "{{ provider }}"
      delegate_to: localhost
      when: 'staging_tag not in group_names'

    - name: Load staging LTM configuration
      bigip_config:
        merge_content: "{{ lookup('file', '{{ base_git_repo_path }}/staging/LTM_configuration/tmsh.config' ) }}"
        provider: "{{ provider }}"
      delegate_to: localhost
      when: 'staging_tag in group_names'

    - name: Save master TMSH configuration
      bigip_config:
        save: yes 
        provider: "{{ provider }}"
      delegate_to: localhost
      when: 'staging_tag not in group_names'

    - name: Save staging TMSH configuration
      bigip_config:
        save: yes 
        provider: "{{ provider }}"
      delegate_to: localhost
      when: 'staging_tag in group_names'